name: Ubuntu Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xrdp and configure for root
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
          echo 'root:abc13726931956' | sudo chpasswd
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm64.zip
          unzip ngrok-stable-linux-arm64.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/

      - name: cloudflare
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
          sudo dpkg -i cloudflared.deb && 
          sudo cloudflared service install eyJhIjoiMGU2MDk0M2E3YjM5Yzk5OTQyMTY5MmQ0ODg2ZWFlNTQiLCJ0IjoiOTE5Y2VjYzAtYjljNi00YTkyLThjOGMtNjNlNWE1NmY1MTg2IiwicyI6Ik1qWmpaalprTmpjdE5tSTJZUzAwTlRaa0xUazJNalV0TVRWbU9EYzBaR0ZpTVRrMSJ9
          sleep 5
          public_ip=$(curl -s http://localhost:443/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Public IP Address: $public_ip"

      - name: Keep Alive
        run: |
          while true; do
            echo "Workflow is running..."
            sleep 5184000  # Sleep for 1 hour
          done
